fixup! persist tedge and service state in mender state scripts

diff --git a/mender/recipes-mender/tedge-state-scripts/tedge-state-scripts/backup_restore b/mender/recipes-mender/tedge-state-scripts/tedge-state-scripts/backup_restore
--- a/mender/recipes-mender/tedge-state-scripts/tedge-state-scripts/backup_restore
+++ b/mender/recipes-mender/tedge-state-scripts/tedge-state-scripts/backup_restore
@@ -29,6 +29,96 @@ backup() {
     tar -cvpzf "$BACKUP_DIR/etc_tedge.tgz" /etc/tedge/
 }
 
+backup_part_to_part() {
+    #
+    # Copy files directly from partition 1 to 2
+    #
+    echo "$(mender show-artifact): Running $(basename "$0")" >&2
+    FW_PRINTENV=$(which fw_printenv)
+    if [ ! -x "$FW_PRINTENV" ]; then
+        exit 1
+    fi
+
+    current=$("$FW_PRINTENV" mender_boot_part | awk -F = '{ print $2 }')
+
+    if [ "$current" = "2" ]; then
+        newroot=/dev/mmcblk0p3
+    elif [ "$current" = "3" ]; then
+        newroot=/dev/mmcblk0p2
+    else
+        echo "Unexpected current root: $current" >&2
+        exit 1
+    fi
+
+    # force unmounting any previously mounted partition (left over from any failed run)
+    umount /mnt >/dev/null 2>&1 || true
+    if ! mount "$newroot" /mnt; then
+        echo "Failed to mount $newroot" >&2
+        exit 1
+    fi
+
+    # wait for mountpoint
+    count=0
+    while ! mountpoint -q /mnt
+    do
+        sleep 1
+        if [ "$count" -ge 30 ]; then
+            echo "timed out waiting for mount to be ready" >&2
+            exit 1
+        fi
+        count=$((count + 1))
+    done
+
+    # tedge files
+    if [ -d /etc/tedge ]; then
+
+        if [ ! -d /mnt/etc/tedge ]; then
+            mkdir -p /mnt/etc/tedge
+            chown tedge:tedge /mnt/etc/tedge
+        fi
+        cp -Rfa /etc/tedge/* /mnt/etc/tedge
+
+        # data files
+        VAR_TEDGE=$(tedge config get data.path)
+        NEW_VAR_TEDGE="/mnt$VAR_TEDGE"
+
+        if [ ! -d "$NEW_VAR_TEDGE" ]; then
+            mkdir -p "$NEW_VAR_TEDGE"
+            chown tedge:tedge "$NEW_VAR_TEDGE"
+        fi
+        cp -Rfa "$VAR_TEDGE"/* "$NEW_VAR_TEDGE"
+    fi
+
+    # ssh authorized keys
+    if [ -d /home/root/.ssh ]; then
+        if [ -f /home/root/.ssh/authorized_keys ]; then
+            if [ -f /mnt/home/root/.ssh/authorized_keys ]; then
+                cp /home/root/.ssh/authorized_keys /mnt/home/root/.ssh/authorized_keys
+            else
+                echo "Found authorized_keys in new root, skipping copy" >&2
+            fi
+        else
+            echo "No authorized keys in current root, skipping copy" >&2
+        fi
+    fi
+
+    # ssh configuration
+    if [ -d /mnt/etc/ssh ]; then
+        keys=$(ls -l /mnt/etc/ssh/*key* 2>/dev/null | wc -l)
+
+        if [ "$keys" -eq 0 ]; then
+            cp /etc/ssh/*key* /mnt/etc/ssh
+        else
+            echo "Found ssh keys in new root, skipping copy" >&2
+        fi
+    else
+        echo "Failed to find a /etc/ssh on newroot partition" >&2
+        exit 1
+    fi
+
+    umount "$newroot"
+}
+
 ###################
 # restore
 ###################
@@ -38,7 +128,7 @@ restore() {
         exit 1
     fi
 
-    tar xzpf "$BACKUP_DIR/etc_tedge.tgz" /etc/tedge
+    # tar xzpf "$BACKUP_DIR/etc_tedge.tgz" /etc/tedge
 
     if command -V systemctl >/dev/null 2>&1; then
         while read -r UNIT_NAME; do
@@ -75,6 +165,7 @@ SCRIPT_NAME="$(basename "$0")"
 case "$SCRIPT_NAME" in
     *ArtifactInstall_Leave*)
         backup
+        backup_part_to_part
         ;;
 
     *ArtifactCommit_Enter*)
